### ISSUE TITLE
 lp-dp-beta2 分支 can通讯错误

### ISSUE THREAD

**Issue by lwd2136** [eFiniLan/legacypilot#7]
### Describe the bug

我想向您报告的问题是关于can通讯错误的提示，相关设备的车型为2019款的卡罗拉双擎。但如果分支选择release2_e2e的话，不会报错。

控制台显示
opendbc/can/parser.cc: 0x3F6 'BSM' TIMED OUT

此外，我还对原车额外进行了BSM的原厂加装。

希望您能尽快帮助我解决这个问题。感谢您的理解与支持。

祝顺利，

Alex

### Provide a route where the issue occurs

no

### openpilot version

 lp-dp 2023-09-19T

**Comment by eFiniLan** [comment]
@lwd2136 Hi Alex 謝謝你的提問，這個主要是因為 opendbc 這個模塊的變化：
在早期的 dp (release2 / release2-e2e) 中，我們把部分的 CAN 信號驗證代碼拿掉。
但在 lp-dp-beta2 ，我們希望能夠盡量減少這樣的修改，所以又把驗證代碼放了回去。

我會在下個版本再把它們遮蔽起來看看 :)

**Comment by lwd2136** [comment]
请问有辦法辨識到bsm的訊號麼，因為畢竟也是使用原廠的系統。之前似乎看過自動輔助變換車道時候，如果bsm監測到有後方來車，會取消輔助變換車道。

**Comment by eFiniLan** [comment]
> 请问有辦法辨識到bsm的訊號麼，因為畢竟也是使用原廠的系統。之前似乎看過自動輔助變換車道時候，如果bsm監測到有後方來車，會取消輔助變換車道。

我下一個版本會把訊號錯誤的問題 "opendbc/can/parser.cc: 0x3F6 'BSM' TIMED OUT" 遮蔽 起來，到時再麻煩你試試 :)
